### ISSUE TITLE
Implement Roles Evm members statistics related functions

### ISSUE THREAD

**Issue by siriusyim** [dataswap/dataswapjs#255]
### Improvement Suggestion

Implement Roles Evm members statistics related functions
1.Data type design(include datastore)
2.Function realization

**Comment by Kennynauh** [comment]
Community member details page

**Comment by Kennynauh** [comment]
Community member header data design
Community member master list data design

**Comment by siriusyim** [comment]
ref #266 
#268 
#269 
#270 
#271 
#272
