### ISSUE TITLE
definition the datastore repo(including model) for 5 interface

### ISSUE THREAD

**Issue by waynewyang** [dataswap/dataswapjs#57]
- dataset requirement,  do it after #46 done
- matching target , do it after #48  done
- matching metadata,  do it after #47 done
- car,  do it after #50  done
- carreplica,  do it after #49 done

**Comment by siriusyim** [comment]
Issues decomposed into 
#106 
#107
#108
#109
#110

**Comment by siriusyim** [comment]
Issues decomposed into 
#106 
#107
#108
#109
#110
